---
name: "Bump Go Version"

on:
  push:
    branches: [master, release]
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  bump-go:
    name: "Bump Go Version"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: "Bump Go Version"
        run: |
          cp .github/bump-go-version.sh .
          bash bump-go-version.sh
          rm -f bump-go-version.sh || exit 1
          if ! git diff --quiet --exit-code; then
            echo "RENEW=1" >> "$GITHUB_ENV"
          fi

      - name: "Upload commit to repository"
        uses: stefanzweifel/git-auto-commit-action@v7
        if: env.RENEW == '1'
        with:
          commit_message: "chore: bump go version by github actions"
          commit_options: "--no-verify --signoff"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
